Repository ISIS3510-202420-T12/flutter-app, pull requests merged in 2024-11, with the labels that each got.

#37 Network service and memory strategies
  wearabouts/lib/core/repositories/clothesRepository.dart
  wearabouts/lib/core/repositories/model/user.dart
  wearabouts/lib/core/widgets/appBar.dart
  wearabouts/lib/features/auth/viewmodel/userViewModel.dart
  wearabouts/lib/features/donation/view/pages/donationMapPage.dart
  wearabouts/lib/features/donation/viewModel/donationViewModel.dart
  wearabouts/lib/features/favorites/viewModel/favoritesViewModel.dart
  wearabouts/lib/features/home/view/pages/clotheDetailPage.dart
  wearabouts/lib/features/home/view/widgets/categoryTab.dart
  wearabouts/lib/features/home/view/widgets/vendorProfileCard.dart
  wearabouts/lib/features/home/viewmodel/marketPlaceViewModel.dart
  wearabouts/lib/features/notifications/view/pages/notificationsPage.dart
  wearabouts/lib/features/notifications/view/widgets/notificationCard.dart
  wearabouts/lib/features/notifications/viewModel/notificationsViewModel.dart
  wearabouts/lib/main.dart
  wearabouts/lib/services/localNotifications/notificacionService.dart
  wearabouts/lib/services/networkChecker/networkService.dart
  wearabouts/pubspec.lock
  wearabouts/pubspec.yaml
Labels: feature

#41 EC
  .gitignore
  wearabouts/lib/core/Viewframes/HomeFrame.dart
  wearabouts/lib/features/donation/view/pages/donationMapPage.dart
  wearabouts/lib/features/donation/view/pages/donationPage.dart
  wearabouts/lib/features/donation/viewModel/donationViewModel.dart
  wearabouts/lib/features/home/view/pages/checkoutPage.dart
  wearabouts/lib/features/home/viewmodel/marketPlaceViewModel.dart
  wearabouts/macos/Flutter/GeneratedPluginRegistrant.swift
  wearabouts/windows/flutter/generated_plugin_registrant.cc
  wearabouts/windows/flutter/generated_plugins.cmake
Labels: GUI

#43 Threaded sorting
  wearabouts/lib/features/home/view/pages/homePage.dart
  wearabouts/lib/features/home/viewmodel/marketPlaceViewModel.dart
Labels: Performance

#46 Market filter bug fix
  wearabouts/lib/features/favorites/view/widgets/favoritesCard.dart
  wearabouts/lib/features/home/view/pages/homePage.dart
  wearabouts/lib/features/home/view/widgets/categoryTab.dart
  wearabouts/lib/features/home/viewmodel/marketPlaceViewModel.dart
  wearabouts/lib/main.dart
Labels: bug

#48 Cache images
  .gitignore
  wearabouts/lib/core/Viewframes/HomeFrame.dart
  wearabouts/lib/features/auth/view/pages/authPage.dart
  wearabouts/lib/features/home/view/pages/checkoutPage.dart
  wearabouts/lib/features/home/view/pages/homePage.dart
  wearabouts/lib/features/home/view/widgets/clothesCard.dart
  wearabouts/lib/features/home/viewmodel/marketPlaceViewModel.dart
  wearabouts/pubspec.lock
  wearabouts/pubspec.yaml
Labels: bug
